[project]
name = "generate-woo-pydantic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datamodel-code-generator>=0.26.5",
    "pydantic>=2.10.6",
    "woocommerce>=3.0.0",
]
